import Footer from "../../components/footer";
import Header from "../../components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import ReduxProvider from "@/store/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta
          name="description"
          content="Free Web tutorials"
        />
        <meta
          name="keywords"
          content="HTML, CSS, JavaScript, Ecommerce"
        />
        <meta
          name="author"
          content="Shahzaib Noor"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <div className="">
            <header>
              <Header />
            </header>
            <main className="flex flex-wrap p-12 md:p-24">
              {children}
            </main>
            <footer>
              <Footer />
            </footer>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
