import Footer from "../../components/footer";
import Header from "../../components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import ReduxProvider from "@/store/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="">
            <header>
              <Header />
            </header>
            <main className="flex flex-wrap p-12 md:p-24">
              {children}
            </main>
            <footer>
              <Footer />
            </footer>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
